[package]
name = "houdini-debug-logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hapi-rs = "0.10.0"
anyhow = "1.0.71"
serde_json = "1.0.96"
glam = ">=0.21.3"